insert into movie (id, title, image, year) values(nextval('movie_seq'), 'Full metal jacket', 'https://pad.mymovies.it/filmclub/2006/04/020/fmj.jpg', 1987);
insert into movie (id, title, image, year) values(nextval('movie_seq'), 'Non e'' un paese per vecchi', 'https://aforismi.meglio.it/img/film/Non_%C3%A8_un_paese_per_vecchi.jpg',2007);
insert into movie (id, title, image, year) values(nextval('movie_seq'), 'The founder', 'https://pad.mymovies.it/filmclub/2016/03/235/fmj.jpg',2016);
insert into movie (id, title, image, year) values(nextval('movie_seq'), 'Harry Potter e la pietra filosofale', 'https://pad.mymovies.it/filmclub/2001/12/001/fmj.jpg',2001);
insert into movie (id, title, image, year) values(nextval('movie_seq'), 'Il pianeta delle scimmie', 'https://media-assets.wired.it/photos/615daad62707bc568326abfa/master/w_1600,c_limit/war-for-the-planet-of-the-apes1.jpg',2001);
insert into movie (id, title, image, year) values(nextval('movie_seq'), 'Lo chiamavano Jeeg Robot', 'https://www.rai.it/dl/img/2016/02/23/1280x720_1456237082397_jeegrobot.jpg',2015);
insert into movie (id, title, image, year) values(nextval('movie_seq'), 'Yesterday', 'https://citynews-today.stgy.ovh/~media/horizontal-mid/20648620006811/yesterday-film-poster-movie-universal-pictures-2.jpg',2019);

insert into artist (id, name, surname, url_of_picture, date_of_birth) values(nextval('artist_seq'), 'Tim', 'Burton', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Tim_Burton_by_Gage_Skidmore.jpg/440px-Tim_Burton_by_Gage_Skidmore.jpg','1958-08-25');
insert into artist (id, name, surname, url_of_picture, date_of_birth) values(nextval('artist_seq'), 'Himesh', 'Patel', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Himesh_Patel_2019_%28cropped%29.jpg/440px-Himesh_Patel_2019_%28cropped%29.jpg','1990-10-13');
insert into artist (id, name, surname, url_of_picture, date_of_birth) values(nextval('artist_seq'), 'Danny', 'Boyle', 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Danny_Boyle_2019_%28cropped%29.jpg/440px-Danny_Boyle_2019_%28cropped%29.jpg','1956-10-20');
insert into artist (id, name, surname, url_of_picture, date_of_birth) values(nextval('artist_seq'), 'Tim', 'Roth', 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Tim_Roth_by_Gage_Skidmore_2.jpg/440px-Tim_Roth_by_Gage_Skidmore_2.jpg','1961-05-14');
insert into artist (id, name, surname, url_of_picture, date_of_birth) values(nextval('artist_seq'), 'Michael', 'Keaton', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Michael_Keaton_by_Gage_Skidmore.jpg/440px-Michael_Keaton_by_Gage_Skidmore.jpg','1951-09-05');
insert into artist (id, name, surname, url_of_picture, date_of_birth) values(nextval('artist_seq'), 'Stanley', 'Kubrick', 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Kubrick_on_the_set_of_Barry_Lyndon_%281975_publicity_photo%29_crop.jpg/440px-Kubrick_on_the_set_of_Barry_Lyndon_%281975_publicity_photo%29_crop.jpg','1928-07-26');
insert into artist (id, name, surname, url_of_picture, date_of_birth) values(nextval('artist_seq'), 'Ronald Lee', 'Ermey', 'https://upload.wikimedia.org/wikipedia/commons/4/4f/RLeeErmeyCrop.jpeg','1944-03-24');
insert into artist (id, name, surname, url_of_picture, date_of_birth) values(nextval('artist_seq'), 'Claudio', 'Santamaria', 'https://upload.wikimedia.org/wikipedia/commons/9/9d/Claudio_Santamaria.jpg','1974-07-22');
insert into artist (id, name, surname, url_of_picture, date_of_birth) values(nextval('artist_seq'), 'Gabriele', 'Mainetti', 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Gabriele_Mainetti%2C_September_2017.jpg/440px-Gabriele_Mainetti%2C_September_2017.jpg','1976-11-07');
insert into artist (id, name, surname, url_of_picture, date_of_birth, date_of_death) values(nextval('artist_seq'), 'Ronald', 'Lee Ermey', 'https://upload.wikimedia.org/wikipedia/commons/4/4f/RLeeErmeyCrop.jpeg','1944-03-24', '2018-04-15');
insert into artist (id, name, surname, url_of_picture, date_of_birth) values(nextval('artist_seq'), 'Vincent', E'D\'Onofrio', 'https://upload.wikimedia.org/wikipedia/commons/8/8f/Vincent_D%27Onofrio_Photo_Op_GalaxyCon_Richmond_2023.jpg','1959-06-30');
